INSERT INTO user (firstname, lastname, D_O_B, email, phone, password) VALUES("Miriah", "Rosenbaum", "1990-04-20", "tad73@mccullough-upton.com", "1-762-998-9378", "password123");
INSERT INTO user (firstname, lastname, D_O_B, email, phone, password) VALUES("Dwight", "Stamm", "2006-11-12", "yoelohara@botsford.com", "1-047-299-0059x3240", "password123");
INSERT INTO user (firstname, lastname, D_O_B, email, phone, password) VALUES("Tayla", "White", "1972-09-23", "irippin@moen.com", "04379954200", "password123");
INSERT INTO user (firstname, lastname, D_O_B, email, phone, password) VALUES("Jess", "Littel", "1987-11-10", "callie08@gmail.com", "(948)461-6857", "password123");
INSERT INTO user (firstname, lastname, D_O_B, email, phone, password) VALUES("Jerimy", "Brakus", "1989-02-12", "jacobishae@runolfsdottir.com", "129-888-1367", "password123");
INSERT INTO user (firstname, lastname, D_O_B, email, phone, password) VALUES("Emery", "Robel", "2008-05-19", "shantell04@hotmail.com", "914.255.0229x717", "password123");
INSERT INTO user (firstname, lastname, D_O_B, email, phone, password) VALUES("Luetta", "Schuster", "1993-05-30", "ondrickaaline@hilpert.net", "(456)158-2868x3088", "password123");
INSERT INTO user (firstname, lastname, D_O_B, email, phone, password) VALUES("Moshe", "Corwin", "2001-06-02", "reubin05@kemmer.com", "1-812-695-3908", "password123");
INSERT INTO user (firstname, lastname, D_O_B, email, phone, password) VALUES("Jarrett", "Windler", "1976-02-06", "franeckizoe@gmail.com", "444.180.2024x931", "password123");
INSERT INTO user (firstname, lastname, D_O_B, email, phone, password) VALUES("Akeelah", "Hilpert", "1976-09-08", "kutchroberta@gmail.com", "(603)747-1215x957", "password123");
INSERT INTO profile (user_id, profile_id, diet_type) VALUES(1, 1, "Diabetic");
INSERT INTO profile (user_id, profile_id, diet_type) VALUES(2, 2, "Classic");
INSERT INTO profile (user_id, profile_id, diet_type) VALUES(3, 3, "Classic");
INSERT INTO profile (user_id, profile_id, diet_type) VALUES(4, 4, "Classic");
INSERT INTO profile (user_id, profile_id, diet_type) VALUES(5, 5, "Diabetic");
INSERT INTO profile (user_id, profile_id, diet_type) VALUES(6, 6, "Vegan");
INSERT INTO profile (user_id, profile_id, diet_type) VALUES(7, 7, "Classic");
INSERT INTO profile (user_id, profile_id, diet_type) VALUES(8, 8, "Vegan");
INSERT INTO recipe (recipe_name, recipe_picture, prep_time, cook_time, servings, diet_type) VALUES("Restaurant-Style Salsa", "Kimari Nelson_2018-04-04-03-59-45_pexels-photo-247685.png", "22 Minutes", "25 Minutes", 2, "Diabetic");
INSERT INTO recipe (recipe_name, recipe_picture, prep_time, cook_time, servings, diet_type) VALUES("Best-ever brownies", "Kimari Nelson_2018-04-04-03-59-45_pexels-photo-247685.png", "51 Minutes", "95 Minutes", 3, "Vegetarian");
INSERT INTO recipe (recipe_name, recipe_picture, prep_time, cook_time, servings, diet_type) VALUES("Classic scones with jam & clotted cream", "Kimari Nelson_2018-04-04-03-59-45_pexels-photo-247685.png", "40 Minutes", "34 Minutes", 3, "Vegetarian");
INSERT INTO recipe (recipe_name, recipe_picture, prep_time, cook_time, servings, diet_type) VALUES("Spiced carrot & lentil soup", "Kimari Nelson_2018-04-04-03-59-45_pexels-photo-247685.png", "55 Minutes", "46 Minutes", 4, "Classic");
INSERT INTO recipe (recipe_name, recipe_picture, prep_time, cook_time, servings, diet_type) VALUES("Chicken & chorizo jambalaya", "Kimari Nelson_2018-04-04-03-59-45_pexels-photo-247685.png", "22 Minutes", "71 Minutes", 5, "Classic");
INSERT INTO recipe (recipe_name, recipe_picture, prep_time, cook_time, servings, diet_type) VALUES("Shrimp Scampi with Linguini", "Kimari Nelson_2018-04-04-03-59-45_pexels-photo-247685.png", "59 Minutes", "107 Minutes", 1, "Diabetic");
INSERT INTO recipe (recipe_name, recipe_picture, prep_time, cook_time, servings, diet_type) VALUES("One-pot chicken chasseur", "Kimari Nelson_2018-04-04-03-59-45_pexels-photo-247685.png", "15 Minutes", "120 Minutes", 5, "Classic");
INSERT INTO recipe (recipe_name, recipe_picture, prep_time, cook_time, servings, diet_type) VALUES("Shrimp Scampi with Linguini", "Kimari Nelson_2018-04-04-03-59-45_pexels-photo-247685.png", "20 Minutes", "18 Minutes", 2, "Vegan");
INSERT INTO recipe (recipe_name, recipe_picture, prep_time, cook_time, servings, diet_type) VALUES("Cheesecake", "Kimari Nelson_2018-04-04-03-59-45_pexels-photo-247685.png", "14 Minutes", "88 Minutes", 5, "Vegan");
INSERT INTO recipe (recipe_name, recipe_picture, prep_time, cook_time, servings, diet_type) VALUES("Baked Potato Casserole", "Kimari Nelson_2018-04-04-03-59-45_pexels-photo-247685.png", "13 Minutes", "51 Minutes", 5, "Diabetic");
INSERT INTO ingredients (ingredient_name) VALUES("asparagus");
INSERT INTO ingredients (ingredient_name) VALUES("apples");
INSERT INTO ingredients (ingredient_name) VALUES("avacado");
INSERT INTO ingredients (ingredient_name) VALUES("alfalfa");
INSERT INTO ingredients (ingredient_name) VALUES("acorn squash");
INSERT INTO ingredients (ingredient_name) VALUES("almond");
INSERT INTO ingredients (ingredient_name) VALUES("arugala");
INSERT INTO ingredients (ingredient_name) VALUES("artichoke");
INSERT INTO ingredients (ingredient_name) VALUES("applesauce");
INSERT INTO ingredients (ingredient_name) VALUES("asian noodles");
INSERT INTO ingredients (ingredient_name) VALUES("antelope");
INSERT INTO ingredients (ingredient_name) VALUES("ahi tuna");
INSERT INTO ingredients (ingredient_name) VALUES("albacore tuna");
INSERT INTO ingredients (ingredient_name) VALUES("Apple juice");
INSERT INTO ingredients (ingredient_name) VALUES("Avocado roll");
INSERT INTO ingredients (ingredient_name) VALUES("Bruscetta");
INSERT INTO ingredients (ingredient_name) VALUES("bacon");
INSERT INTO ingredients (ingredient_name) VALUES("black beans");
INSERT INTO ingredients (ingredient_name) VALUES("bagels");
INSERT INTO ingredients (ingredient_name) VALUES("baked beans");
INSERT INTO ingredients (ingredient_name) VALUES("BBQ");
INSERT INTO ingredients (ingredient_name) VALUES("bison");
INSERT INTO ingredients (ingredient_name) VALUES("barley");
INSERT INTO ingredients (ingredient_name) VALUES("beer");
INSERT INTO ingredients (ingredient_name) VALUES("bisque");
INSERT INTO ingredients (ingredient_name) VALUES("bluefish");
INSERT INTO ingredients (ingredient_name) VALUES("bread");
INSERT INTO ingredients (ingredient_name) VALUES("broccoli");
INSERT INTO ingredients (ingredient_name) VALUES("buritto");
INSERT INTO ingredients (ingredient_name) VALUES("babaganoosh");
INSERT INTO ingredients (ingredient_name) VALUES("Cabbage");
INSERT INTO ingredients (ingredient_name) VALUES("cake");
INSERT INTO ingredients (ingredient_name) VALUES("carrots");
INSERT INTO ingredients (ingredient_name) VALUES("carne asada");
INSERT INTO ingredients (ingredient_name) VALUES("celery");
INSERT INTO ingredients (ingredient_name) VALUES("cheese");
INSERT INTO ingredients (ingredient_name) VALUES("chicken");
INSERT INTO ingredients (ingredient_name) VALUES("catfish");
INSERT INTO ingredients (ingredient_name) VALUES("chips");
INSERT INTO ingredients (ingredient_name) VALUES("chocolate");
INSERT INTO ingredients (ingredient_name) VALUES("chowder");
INSERT INTO ingredients (ingredient_name) VALUES("clams");
INSERT INTO ingredients (ingredient_name) VALUES("coffee");
INSERT INTO ingredients (ingredient_name) VALUES("cookies");
INSERT INTO ingredients (ingredient_name) VALUES("corn");
INSERT INTO ingredients (ingredient_name) VALUES("cupcakes");
INSERT INTO ingredients (ingredient_name) VALUES("crab");
INSERT INTO ingredients (ingredient_name) VALUES("curry");
INSERT INTO ingredients (ingredient_name) VALUES("cereal");
INSERT INTO ingredients (ingredient_name) VALUES("chimichanga");
INSERT INTO ingredients (ingredient_name) VALUES("dates");
INSERT INTO ingredients (ingredient_name) VALUES("dips");
INSERT INTO ingredients (ingredient_name) VALUES("duck");
INSERT INTO ingredients (ingredient_name) VALUES("dumplings");
INSERT INTO ingredients (ingredient_name) VALUES("donuts");
INSERT INTO ingredients (ingredient_name) VALUES("eggs");
INSERT INTO ingredients (ingredient_name) VALUES("enchilada");
INSERT INTO ingredients (ingredient_name) VALUES("eggrolls");
INSERT INTO ingredients (ingredient_name) VALUES("English muffins");
INSERT INTO ingredients (ingredient_name) VALUES("edimame");
INSERT INTO ingredients (ingredient_name) VALUES("eel sushi");
INSERT INTO ingredients (ingredient_name) VALUES("fajita");
INSERT INTO ingredients (ingredient_name) VALUES("falafel");
INSERT INTO ingredients (ingredient_name) VALUES("fish");
INSERT INTO ingredients (ingredient_name) VALUES("franks");
INSERT INTO ingredients (ingredient_name) VALUES("fondu");
INSERT INTO ingredients (ingredient_name) VALUES("French toast");
INSERT INTO ingredients (ingredient_name) VALUES("French dip");
INSERT INTO ingredients (ingredient_name) VALUES("Garlic");
INSERT INTO ingredients (ingredient_name) VALUES("ginger");
INSERT INTO ingredients (ingredient_name) VALUES("gnocchi");
INSERT INTO ingredients (ingredient_name) VALUES("goose");
INSERT INTO ingredients (ingredient_name) VALUES("granola");
INSERT INTO ingredients (ingredient_name) VALUES("grapes");
INSERT INTO ingredients (ingredient_name) VALUES("green beans");
INSERT INTO ingredients (ingredient_name) VALUES("Guancamole");
INSERT INTO ingredients (ingredient_name) VALUES("gumbo");
INSERT INTO ingredients (ingredient_name) VALUES("grits");
INSERT INTO ingredients (ingredient_name) VALUES("Graham crackers");
INSERT INTO ingredients (ingredient_name) VALUES("ham");
INSERT INTO ingredients (ingredient_name) VALUES("halibut");
INSERT INTO ingredients (ingredient_name) VALUES("hamburger");
INSERT INTO ingredients (ingredient_name) VALUES("honey");
INSERT INTO ingredients (ingredient_name) VALUES("huenos rancheros");
INSERT INTO ingredients (ingredient_name) VALUES("hash browns");
INSERT INTO ingredients (ingredient_name) VALUES("hot dogs");
INSERT INTO ingredients (ingredient_name) VALUES("haiku roll");
INSERT INTO ingredients (ingredient_name) VALUES("hummus");
INSERT INTO ingredients (ingredient_name) VALUES("ice cream");
INSERT INTO ingredients (ingredient_name) VALUES("Irish stew");
INSERT INTO ingredients (ingredient_name) VALUES("Indian food");
INSERT INTO ingredients (ingredient_name) VALUES("Italian bread");
INSERT INTO ingredients (ingredient_name) VALUES("jambalaya");
INSERT INTO ingredients (ingredient_name) VALUES("jelly / jam");
INSERT INTO ingredients (ingredient_name) VALUES("jerky");
INSERT INTO ingredients (ingredient_name) VALUES("kale");
INSERT INTO ingredients (ingredient_name) VALUES("kabobs");
INSERT INTO ingredients (ingredient_name) VALUES("ketchup");
INSERT INTO ingredients (ingredient_name) VALUES("kiwi");
INSERT INTO ingredients (ingredient_name) VALUES("kidney beans");
INSERT INTO ingredients (ingredient_name) VALUES("kingfish");
INSERT INTO ingredients (ingredient_name) VALUES("lobster");
INSERT INTO ingredients (ingredient_name) VALUES("Lamb");
INSERT INTO ingredients (ingredient_name) VALUES("Linguine");
INSERT INTO ingredients (ingredient_name) VALUES("Lasagna");
INSERT INTO ingredients (ingredient_name) VALUES("Meatballs");
INSERT INTO ingredients (ingredient_name) VALUES("Moose");
INSERT INTO ingredients (ingredient_name) VALUES("Milk");
INSERT INTO ingredients (ingredient_name) VALUES("Milkshake");
INSERT INTO ingredients (ingredient_name) VALUES("Noodles");
INSERT INTO ingredients (ingredient_name) VALUES("Ostrich");
INSERT INTO ingredients (ingredient_name) VALUES("Pizza");
INSERT INTO ingredients (ingredient_name) VALUES("Pepperoni");
INSERT INTO ingredients (ingredient_name) VALUES("Porter");
INSERT INTO ingredients (ingredient_name) VALUES("Pancakes");
INSERT INTO ingredients (ingredient_name) VALUES("Quesadilla");
INSERT INTO ingredients (ingredient_name) VALUES("Quiche");
INSERT INTO ingredients (ingredient_name) VALUES("Reuben");
INSERT INTO ingredients (ingredient_name) VALUES("Spinach");
INSERT INTO ingredients (ingredient_name) VALUES("Spaghetti");
INSERT INTO ingredients (ingredient_name) VALUES("Tater tots");
INSERT INTO ingredients (ingredient_name) VALUES("Toast");
INSERT INTO ingredients (ingredient_name) VALUES("Venison");
INSERT INTO ingredients (ingredient_name) VALUES("Waffles");
INSERT INTO ingredients (ingredient_name) VALUES("Wine");
INSERT INTO ingredients (ingredient_name) VALUES("Walnuts");
INSERT INTO ingredients (ingredient_name) VALUES("Yogurt");
INSERT INTO ingredients (ingredient_name) VALUES("Ziti");
INSERT INTO ingredients (ingredient_name) VALUES("Zucchini");
INSERT INTO needs (ingredient_id, recipe_id, measurement_id, quantity) VALUES(61, 1, 8, 8);
INSERT INTO needs (ingredient_id, recipe_id, measurement_id, quantity) VALUES(21, 1, 3, 4);
INSERT INTO needs (ingredient_id, recipe_id, measurement_id, quantity) VALUES(111, 1, 6, 8);
INSERT INTO needs (ingredient_id, recipe_id, measurement_id, quantity) VALUES(52, 2, 2, 1);
INSERT INTO needs (ingredient_id, recipe_id, measurement_id, quantity) VALUES(17, 2, 8, 8);
INSERT INTO needs (ingredient_id, recipe_id, measurement_id, quantity) VALUES(92, 2, 4, 4);
INSERT INTO needs (ingredient_id, recipe_id, measurement_id, quantity) VALUES(53, 2, 4, 4);
INSERT INTO needs (ingredient_id, recipe_id, measurement_id, quantity) VALUES(34, 3, 4, 8);
INSERT INTO needs (ingredient_id, recipe_id, measurement_id, quantity) VALUES(22, 3, 5, 3);
INSERT INTO needs (ingredient_id, recipe_id, measurement_id, quantity) VALUES(9, 3, 4, 10);
INSERT INTO needs (ingredient_id, recipe_id, measurement_id, quantity) VALUES(105, 4, 5, 4);
INSERT INTO needs (ingredient_id, recipe_id, measurement_id, quantity) VALUES(43, 4, 2, 3);
INSERT INTO needs (ingredient_id, recipe_id, measurement_id, quantity) VALUES(63, 4, 2, 5);
INSERT INTO needs (ingredient_id, recipe_id, measurement_id, quantity) VALUES(109, 5, 6, 7);
INSERT INTO needs (ingredient_id, recipe_id, measurement_id, quantity) VALUES(112, 5, 8, 8);
INSERT INTO needs (ingredient_id, recipe_id, measurement_id, quantity) VALUES(34, 5, 7, 9);
INSERT INTO needs (ingredient_id, recipe_id, measurement_id, quantity) VALUES(60, 6, 1, 4);
INSERT INTO needs (ingredient_id, recipe_id, measurement_id, quantity) VALUES(10, 6, 7, 5);
INSERT INTO needs (ingredient_id, recipe_id, measurement_id, quantity) VALUES(50, 6, 3, 6);
INSERT INTO needs (ingredient_id, recipe_id, measurement_id, quantity) VALUES(117, 6, 8, 8);
INSERT INTO needs (ingredient_id, recipe_id, measurement_id, quantity) VALUES(19, 7, 7, 9);
INSERT INTO needs (ingredient_id, recipe_id, measurement_id, quantity) VALUES(18, 7, 8, 10);
INSERT INTO needs (ingredient_id, recipe_id, measurement_id, quantity) VALUES(117, 7, 2, 7);
INSERT INTO needs (ingredient_id, recipe_id, measurement_id, quantity) VALUES(60, 8, 8, 3);
INSERT INTO needs (ingredient_id, recipe_id, measurement_id, quantity) VALUES(82, 8, 7, 2);
INSERT INTO needs (ingredient_id, recipe_id, measurement_id, quantity) VALUES(109, 8, 7, 7);
INSERT INTO needs (ingredient_id, recipe_id, measurement_id, quantity) VALUES(37, 9, 1, 1);
INSERT INTO needs (ingredient_id, recipe_id, measurement_id, quantity) VALUES(102, 9, 8, 4);
INSERT INTO needs (ingredient_id, recipe_id, measurement_id, quantity) VALUES(51, 9, 9, 10);
INSERT INTO needs (ingredient_id, recipe_id, measurement_id, quantity) VALUES(68, 10, 7, 7);
INSERT INTO needs (ingredient_id, recipe_id, measurement_id, quantity) VALUES(72, 10, 3, 5);
INSERT INTO needs (ingredient_id, recipe_id, measurement_id, quantity) VALUES(96, 10, 2, 8);
INSERT INTO needs (ingredient_id, recipe_id, measurement_id, quantity) VALUES(39, 10, 8, 4);
INSERT INTO add_recipe (user_id, recipe_id, date_created) VALUES(10, 1, 2018-01-07);
INSERT INTO add_recipe (user_id, recipe_id, date_created) VALUES(10, 2, 2018-12-23);
INSERT INTO add_recipe (user_id, recipe_id, date_created) VALUES(6, 3, 2018-04-04);
INSERT INTO add_recipe (user_id, recipe_id, date_created) VALUES(10, 4, 2018-03-28);
INSERT INTO add_recipe (user_id, recipe_id, date_created) VALUES(1, 5, 2018-05-12);
INSERT INTO add_recipe (user_id, recipe_id, date_created) VALUES(4, 6, 2018-06-20);
INSERT INTO add_recipe (user_id, recipe_id, date_created) VALUES(4, 7, 2018-08-24);
INSERT INTO add_recipe (user_id, recipe_id, date_created) VALUES(4, 8, 2018-12-28);
INSERT INTO add_recipe (user_id, recipe_id, date_created) VALUES(2, 9, 2018-10-06);
INSERT INTO add_recipe (user_id, recipe_id, date_created) VALUES(2, 10, 2018-03-11);
INSERT INTO instruction (recipe_id, step_num, direction) VALUES(1, 1, "cut the honey");
INSERT INTO instruction (recipe_id, step_num, direction) VALUES(1, 2, "rub the Garlic");
INSERT INTO instruction (recipe_id, step_num, direction) VALUES(1, 3, "rub the green beans");
INSERT INTO instruction (recipe_id, step_num, direction) VALUES(1, 4, "rub the hash browns");
INSERT INTO instruction (recipe_id, step_num, direction) VALUES(1, 5, "rub the falafel");
INSERT INTO instruction (recipe_id, step_num, direction) VALUES(2, 1, "Add the cookies");
INSERT INTO instruction (recipe_id, step_num, direction) VALUES(2, 2, "cut the alfalfa");
INSERT INTO instruction (recipe_id, step_num, direction) VALUES(2, 3, "rub the crab");
INSERT INTO instruction (recipe_id, step_num, direction) VALUES(2, 4, "rub the honey");
INSERT INTO instruction (recipe_id, step_num, direction) VALUES(3, 1, "slice the kiwi");
INSERT INTO instruction (recipe_id, step_num, direction) VALUES(3, 2, "rub the alfalfa");
INSERT INTO instruction (recipe_id, step_num, direction) VALUES(3, 3, "rub the huenos rancheros");
INSERT INTO instruction (recipe_id, step_num, direction) VALUES(3, 4, "slice the lobster");
INSERT INTO instruction (recipe_id, step_num, direction) VALUES(3, 5, "season the fish");
INSERT INTO instruction (recipe_id, step_num, direction) VALUES(4, 1, "Add the Apple juice");
INSERT INTO instruction (recipe_id, step_num, direction) VALUES(4, 2, "slice the barley");
INSERT INTO instruction (recipe_id, step_num, direction) VALUES(4, 3, "slice the French toast");
INSERT INTO instruction (recipe_id, step_num, direction) VALUES(4, 4, "slice the falafel");
INSERT INTO instruction (recipe_id, step_num, direction) VALUES(4, 5, "slice the corn");
INSERT INTO instruction (recipe_id, step_num, direction) VALUES(5, 1, "slice the haiku roll");
INSERT INTO instruction (recipe_id, step_num, direction) VALUES(5, 2, "rub the hash browns");
INSERT INTO instruction (recipe_id, step_num, direction) VALUES(5, 3, "rub the grapes");
INSERT INTO instruction (recipe_id, step_num, direction) VALUES(5, 4, "rub the Indian food");
INSERT INTO instruction (recipe_id, step_num, direction) VALUES(5, 5, "season the ketchup");
INSERT INTO instruction (recipe_id, step_num, direction) VALUES(6, 1, "cut the haiku roll");
INSERT INTO instruction (recipe_id, step_num, direction) VALUES(6, 2, "season the asparagus");
INSERT INTO instruction (recipe_id, step_num, direction) VALUES(6, 3, "cut the carne asada");
INSERT INTO instruction (recipe_id, step_num, direction) VALUES(6, 4, "rub the almond");
INSERT INTO instruction (recipe_id, step_num, direction) VALUES(7, 1, "rub the babaganoosh");
INSERT INTO instruction (recipe_id, step_num, direction) VALUES(7, 2, "rub the babaganoosh");
INSERT INTO instruction (recipe_id, step_num, direction) VALUES(7, 3, "rub the green beans");
INSERT INTO instruction (recipe_id, step_num, direction) VALUES(7, 4, "rub the donuts");
INSERT INTO instruction (recipe_id, step_num, direction) VALUES(7, 5, "slice the enchilada");
INSERT INTO instruction (recipe_id, step_num, direction) VALUES(8, 1, "season the bacon");
INSERT INTO instruction (recipe_id, step_num, direction) VALUES(8, 2, "rub the Italian bread");
INSERT INTO instruction (recipe_id, step_num, direction) VALUES(8, 3, "cut the green beans");
INSERT INTO instruction (recipe_id, step_num, direction) VALUES(8, 4, "Add the antelope");
INSERT INTO instruction (recipe_id, step_num, direction) VALUES(8, 5, "cut the Linguine");
INSERT INTO instruction (recipe_id, step_num, direction) VALUES(9, 1, "slice the eggs");
INSERT INTO instruction (recipe_id, step_num, direction) VALUES(9, 2, "rub the chicken");
INSERT INTO instruction (recipe_id, step_num, direction) VALUES(9, 3, "slice the English muffins");
INSERT INTO instruction (recipe_id, step_num, direction) VALUES(9, 4, "season the Pancakes");
INSERT INTO instruction (recipe_id, step_num, direction) VALUES(10, 1, "cut the honey");
INSERT INTO instruction (recipe_id, step_num, direction) VALUES(10, 2, "slice the Graham crackers");
INSERT INTO instruction (recipe_id, step_num, direction) VALUES(10, 3, "season the falafel");
INSERT INTO instruction (recipe_id, step_num, direction) VALUES(10, 4, "slice the ice cream");
INSERT INTO meal (meal_name, meal_type, num_calorie) VALUES("Lemon drizzle cake", "Breakfast", 668);
INSERT INTO meal (meal_name, meal_type, num_calorie) VALUES("Ultimate chocolate cake", "Dinner", 1845);
INSERT INTO meal (meal_name, meal_type, num_calorie) VALUES("Chilli con carne", "Breakfast", 1505);
INSERT INTO meal (meal_name, meal_type, num_calorie) VALUES("Yummy scrummy carrot cake", "Lunch", 1239);
INSERT INTO meal (meal_name, meal_type, num_calorie) VALUES("Best-ever brownies", "Dinner", 676);
INSERT INTO meal (meal_name, meal_type, num_calorie) VALUES("Spiced carrot & lentil soup", "Dinner", 377);
INSERT INTO meal (meal_name, meal_type, num_calorie) VALUES("Chicken & chorizo jambalaya", "Breakfast", 281);
INSERT INTO meal (meal_name, meal_type, num_calorie) VALUES("Summer-in-winter chicken", "Lunch", 1462);
INSERT INTO meal (meal_name, meal_type, num_calorie) VALUES("Spicy root & lentil casserole", "Lunch", 1163);
INSERT INTO meal (meal_name, meal_type, num_calorie) VALUES("Mustard-stuffed chicken", "Breakfast", 518);
INSERT INTO meal (meal_name, meal_type, num_calorie) VALUES("Classic scones with jam & clotted cream", "Lunch", 922);
INSERT INTO meal (meal_name, meal_type, num_calorie) VALUES("Red lentil, chickpea & chilli soup", "Dinner", 1787);
INSERT INTO meal (meal_name, meal_type, num_calorie) VALUES("Falafel burgers", "Lunch", 1642);
INSERT INTO meal (meal_name, meal_type, num_calorie) VALUES("Chicken biryani", "Breakfast", 1663);
INSERT INTO meal (meal_name, meal_type, num_calorie) VALUES("Raspberry Bakewell cake", "Breakfast", 1176);
INSERT INTO meal (meal_name, meal_type, num_calorie) VALUES("Chocolate brownie cake", "Lunch", 712);
INSERT INTO meal (meal_name, meal_type, num_calorie) VALUES("Classic Victoria sandwich", "Breakfast", 1869);
INSERT INTO meal (meal_name, meal_type, num_calorie) VALUES("Creamy courgette lasagne", "Dinner", 842);
INSERT INTO meal (meal_name, meal_type, num_calorie) VALUES("One-pot chicken chasseur", "Dinner", 1474);
INSERT INTO meal (meal_name, meal_type, num_calorie) VALUES("Unbelievably easy mince pies", "Lunch", 1753);
INSERT INTO meal (meal_name, meal_type, num_calorie) VALUES("Asian Grilled Salmon", "Lunch", 1539);
INSERT INTO meal (meal_name, meal_type, num_calorie) VALUES("Chicken Parmesan", "Dinner", 1783);
INSERT INTO meal (meal_name, meal_type, num_calorie) VALUES("Macaroni and Cheese", "Dinner", 974);
INSERT INTO meal (meal_name, meal_type, num_calorie) VALUES("Chicken Pot Pie", "Lunch", 321);
INSERT INTO meal (meal_name, meal_type, num_calorie) VALUES("Chicken Cacciatore", "Dinner", 1303);
INSERT INTO meal (meal_name, meal_type, num_calorie) VALUES("Salisbury Steak", "Dinner", 1783);
INSERT INTO meal (meal_name, meal_type, num_calorie) VALUES("Chocolate Pretzel Peanut Butter Squares", "Breakfast", 1345);
INSERT INTO meal (meal_name, meal_type, num_calorie) VALUES("Blackberry Cobbler", "Breakfast", 1780);
INSERT INTO meal (meal_name, meal_type, num_calorie) VALUES("Roast Chicken", "Lunch", 989);
INSERT INTO meal (meal_name, meal_type, num_calorie) VALUES("Sweet and Sour Chicken", "Lunch", 551);
INSERT INTO meal (meal_name, meal_type, num_calorie) VALUES("Restaurant-Style Salsa", "Lunch", 1508);
INSERT INTO meal (meal_name, meal_type, num_calorie) VALUES("Shrimp Scampi with Linguini", "Breakfast", 1147);
INSERT INTO meal (meal_name, meal_type, num_calorie) VALUES("Parmesan-Crusted Pork Chops", "Breakfast", 1630);
INSERT INTO meal (meal_name, meal_type, num_calorie) VALUES("Broccoli Cheese Soup", "Lunch", 1489);
INSERT INTO makes (meal_id, recipe_id) VALUES(1, 6);
INSERT INTO makes (meal_id, recipe_id) VALUES(2, 8);
INSERT INTO makes (meal_id, recipe_id) VALUES(3, 4);
INSERT INTO makes (meal_id, recipe_id) VALUES(4, 10);
INSERT INTO makes (meal_id, recipe_id) VALUES(5, 9);
INSERT INTO makes (meal_id, recipe_id) VALUES(6, 7);
INSERT INTO makes (meal_id, recipe_id) VALUES(7, 5);
INSERT INTO makes (meal_id, recipe_id) VALUES(8, 8);
INSERT INTO makes (meal_id, recipe_id) VALUES(9, 4);
INSERT INTO makes (meal_id, recipe_id) VALUES(10, 5);
INSERT INTO makes (meal_id, recipe_id) VALUES(11, 7);
INSERT INTO makes (meal_id, recipe_id) VALUES(12, 6);
INSERT INTO makes (meal_id, recipe_id) VALUES(13, 7);
INSERT INTO makes (meal_id, recipe_id) VALUES(14, 8);
INSERT INTO makes (meal_id, recipe_id) VALUES(15, 9);
INSERT INTO makes (meal_id, recipe_id) VALUES(16, 5);
INSERT INTO makes (meal_id, recipe_id) VALUES(17, 8);
INSERT INTO makes (meal_id, recipe_id) VALUES(18, 8);
INSERT INTO makes (meal_id, recipe_id) VALUES(19, 3);
INSERT INTO makes (meal_id, recipe_id) VALUES(20, 1);
INSERT INTO makes (meal_id, recipe_id) VALUES(21, 7);
INSERT INTO makes (meal_id, recipe_id) VALUES(22, 4);
INSERT INTO makes (meal_id, recipe_id) VALUES(23, 2);
INSERT INTO makes (meal_id, recipe_id) VALUES(24, 8);
INSERT INTO makes (meal_id, recipe_id) VALUES(25, 10);
INSERT INTO makes (meal_id, recipe_id) VALUES(26, 7);
INSERT INTO makes (meal_id, recipe_id) VALUES(27, 2);
INSERT INTO makes (meal_id, recipe_id) VALUES(28, 8);
INSERT INTO makes (meal_id, recipe_id) VALUES(29, 8);
INSERT INTO makes (meal_id, recipe_id) VALUES(30, 6);
INSERT INTO makes (meal_id, recipe_id) VALUES(31, 7);
INSERT INTO makes (meal_id, recipe_id) VALUES(32, 4);
INSERT INTO makes (meal_id, recipe_id) VALUES(33, 3);
INSERT INTO makes (meal_id, recipe_id) VALUES(34, 4);
INSERT INTO meal_plan (mealplan_id, end_date) VALUES(1, 2018-10-25);
INSERT INTO meal_plan (mealplan_id, end_date) VALUES(2, 2018-12-23);
INSERT INTO meal_plan (mealplan_id, end_date) VALUES(3, 2018-09-26);
INSERT INTO meal_plan (mealplan_id, end_date) VALUES(4, 2018-07-13);
INSERT INTO meal_plan (mealplan_id, end_date) VALUES(5, 2018-03-08);
INSERT INTO meal_plan (mealplan_id, end_date) VALUES(6, 2018-10-25);
INSERT INTO meal_plan (mealplan_id, end_date) VALUES(7, 2018-03-22);
INSERT INTO meal_plan (mealplan_id, end_date) VALUES(8, 2018-10-02);
INSERT INTO meal_plan (mealplan_id, end_date) VALUES(9, 2018-09-05);
INSERT INTO contains (mealplan_id, meal_id) VALUES(1, 13);
INSERT INTO contains (mealplan_id, meal_id) VALUES(2, 17);
INSERT INTO contains (mealplan_id, meal_id) VALUES(3, 19);
INSERT INTO contains (mealplan_id, meal_id) VALUES(4, 25);
INSERT INTO contains (mealplan_id, meal_id) VALUES(5, 13);
INSERT INTO contains (mealplan_id, meal_id) VALUES(6, 24);
INSERT INTO contains (mealplan_id, meal_id) VALUES(7, 24);
INSERT INTO contains (mealplan_id, meal_id) VALUES(8, 2);
INSERT INTO contains (mealplan_id, meal_id) VALUES(9, 7);
INSERT INTO kitchen (user_id, ingredient_id, quantity) VALUES(1, 46, 4);
INSERT INTO kitchen (user_id, ingredient_id, quantity) VALUES(2, 5, 8);
INSERT INTO kitchen (user_id, ingredient_id, quantity) VALUES(3, 15, 2);
INSERT INTO kitchen (user_id, ingredient_id, quantity) VALUES(4, 35, 4);
INSERT INTO kitchen (user_id, ingredient_id, quantity) VALUES(5, 27, 8);
INSERT INTO kitchen (user_id, ingredient_id, quantity) VALUES(6, 13, 2);
INSERT INTO kitchen (user_id, ingredient_id, quantity) VALUES(7, 22, 6);
INSERT INTO kitchen (user_id, ingredient_id, quantity) VALUES(8, 41, 3);
INSERT INTO kitchen (user_id, ingredient_id, quantity) VALUES(9, 39, 8);
INSERT INTO kitchen (user_id, ingredient_id, quantity) VALUES(1, 35, 5);
INSERT INTO kitchen (user_id, ingredient_id, quantity) VALUES(2, 37, 7);
INSERT INTO kitchen (user_id, ingredient_id, quantity) VALUES(3, 24, 5);
INSERT INTO kitchen (user_id, ingredient_id, quantity) VALUES(4, 38, 2);
INSERT INTO kitchen (user_id, ingredient_id, quantity) VALUES(5, 4, 7);
INSERT INTO kitchen (user_id, ingredient_id, quantity) VALUES(6, 49, 6);
INSERT INTO kitchen (user_id, ingredient_id, quantity) VALUES(7, 27, 6);
INSERT INTO kitchen (user_id, ingredient_id, quantity) VALUES(8, 28, 3);
INSERT INTO kitchen (user_id, ingredient_id, quantity) VALUES(9, 25, 4);
INSERT INTO kitchen (user_id, ingredient_id, quantity) VALUES(1, 13, 7);
INSERT INTO kitchen (user_id, ingredient_id, quantity) VALUES(2, 24, 4);
INSERT INTO kitchen (user_id, ingredient_id, quantity) VALUES(3, 15, 7);
INSERT INTO kitchen (user_id, ingredient_id, quantity) VALUES(4, 43, 5);
INSERT INTO kitchen (user_id, ingredient_id, quantity) VALUES(5, 37, 6);
INSERT INTO kitchen (user_id, ingredient_id, quantity) VALUES(6, 4, 9);
INSERT INTO kitchen (user_id, ingredient_id, quantity) VALUES(7, 21, 9);
INSERT INTO kitchen (user_id, ingredient_id, quantity) VALUES(8, 36, 6);
INSERT INTO kitchen (user_id, ingredient_id, quantity) VALUES(9, 13, 9);
INSERT INTO kitchen (user_id, ingredient_id, quantity) VALUES(1, 46, 4);
INSERT INTO kitchen (user_id, ingredient_id, quantity) VALUES(2, 37, 3);
INSERT INTO kitchen (user_id, ingredient_id, quantity) VALUES(3, 44, 8);
INSERT INTO kitchen (user_id, ingredient_id, quantity) VALUES(4, 16, 9);
INSERT INTO kitchen (user_id, ingredient_id, quantity) VALUES(5, 24, 8);
INSERT INTO kitchen (user_id, ingredient_id, quantity) VALUES(6, 43, 4);
INSERT INTO kitchen (user_id, ingredient_id, quantity) VALUES(7, 29, 4);
INSERT INTO kitchen (user_id, ingredient_id, quantity) VALUES(8, 34, 2);
INSERT INTO kitchen (user_id, ingredient_id, quantity) VALUES(9, 7, 3);
INSERT INTO kitchen (user_id, ingredient_id, quantity) VALUES(1, 24, 9);
INSERT INTO kitchen (user_id, ingredient_id, quantity) VALUES(2, 10, 8);
INSERT INTO kitchen (user_id, ingredient_id, quantity) VALUES(3, 43, 4);
INSERT INTO kitchen (user_id, ingredient_id, quantity) VALUES(4, 40, 6);
INSERT INTO kitchen (user_id, ingredient_id, quantity) VALUES(5, 5, 7);
INSERT INTO kitchen (user_id, ingredient_id, quantity) VALUES(6, 25, 3);
INSERT INTO kitchen (user_id, ingredient_id, quantity) VALUES(7, 46, 4);
INSERT INTO kitchen (user_id, ingredient_id, quantity) VALUES(8, 39, 7);
INSERT INTO kitchen (user_id, ingredient_id, quantity) VALUES(9, 3, 7);
