INSERT INTO measurement (measurement_name) VALUES ("Cup");
INSERT INTO measurement (measurement_name) VALUES ("Teaspoon");
INSERT INTO measurement (measurement_name) VALUES ("Tablespoon");
INSERT INTO measurement (measurement_name) VALUES ("Pound");
INSERT INTO measurement (measurement_name) VALUES ("Quart");
INSERT INTO measurement (measurement_name) VALUES ("Ounce");
INSERT INTO measurement (measurement_name) VALUES ("Pint");
INSERT INTO measurement (measurement_name) VALUES ("Millilitre");
INSERT INTO measurement (measurement_name) VALUES ("Litre");
INSERT INTO measurement (measurement_name) values ('g');
INSERT INTO measurement (measurement_name) values ('cup');
INSERT INTO measurement (measurement_name) values ('kg');
INSERT INTO measurement (measurement_name) values ('n/a');

INSERT INTO ingredient (ingredient_name, food_group) VALUES("apples", "nuts");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("avacado", "shellfish");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("alfalfa", "meat");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("acorn squash", "poultry");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("almond", "Friut");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("arugala", "meat");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("artichoke", "Friut");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("applesauce", "gluten");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("asian noodles", "meat");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("antelope", "nuts");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("ahi tuna", "fish");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("albacore tuna", "meat");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("Apple juice", "beef");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("Avocado roll", "Friut");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("Bruscetta", "shellfish");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("bacon", "meat");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("black beans", "wheat");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("bagels", "Friut");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("baked beans", "dairy");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("BBQ", "shellfish");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("bison", "gluten");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("barley", "dairy");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("beer", "Fats");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("bisque", "Fats");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("bluefish", "shellfish");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("bread", "dairy");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("broccoli", "Friut");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("buritto", "meat");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("babaganoosh", "nuts");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("Cabbage", "dairy");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("cake", "fish");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("carrots", "dairy");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("carne asada", "meat");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("celery", "poultry");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("cheese", "Friut");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("chicken", "beef");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("catfish", "Carbs");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("chips", "fish");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("chocolate", "fish");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("chowder", "fish");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("clams", "Friut");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("coffee", "dairy");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("cookies", "Fats");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("corn", "poultry");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("cupcakes", "wheat");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("crab", "Fats");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("curry", "meat");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("cereal", "dairy");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("chimichanga", "Fats");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("dates", "shellfish");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("dips", "Carbs");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("duck", "shellfish");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("dumplings", "wheat");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("donuts", "Fats");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("eggs", "poultry");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("enchilada", "dairy");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("eggrolls", "wheat");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("English muffins", "poultry");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("edimame", "meat");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("eel sushi", "beef");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("fajita", "beef");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("falafel", "poultry");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("fish", "shellfish");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("franks", "Carbs");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("fondu", "dairy");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("French toast", "Carbs");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("French dip", "beef");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("Garlic", "gluten");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("ginger", "beef");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("gnocchi", "Friut");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("goose", "Friut");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("granola", "Carbs");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("grapes", "Friut");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("green beans", "gluten");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("Guancamole", "poultry");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("gumbo", "fish");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("grits", "meat");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("Graham crackers", "Fats");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("ham", "shellfish");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("halibut", "Carbs");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("hamburger", "dairy");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("honey", "dairy");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("huenos rancheros", "meat");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("hash browns", "fish");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("hot dogs", "pork");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("haiku roll", "shellfish");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("hummus", "shellfish");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("ice cream", "poultry");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("Irish stew", "dairy");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("Indian food", "wheat");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("Italian bread", "Friut");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("jambalaya", "Friut");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("jelly / jam", "dairy");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("jerky", "shellfish");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("kale", "wheat");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("kabobs", "wheat");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("ketchup", "pork");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("kiwi", "Friut");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("kidney beans", "shellfish");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("kingfish", "Carbs");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("lobster", "poultry");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("Lamb", "fish");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("Linguine", "gluten");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("Lasagna", "Carbs");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("Meatballs", "pork");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("Moose", "poultry");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("Milk", "Fats");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("Milkshake", "poultry");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("Noodles", "wheat");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("Ostrich", "nuts");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("Pizza", "nuts");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("Pepperoni", "Friut");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("Porter", "Carbs");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("Pancakes", "nuts");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("Quesadilla", "beef");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("Quiche", "dairy");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("Reuben", "Fats");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("Spinach", "meat");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("Spaghetti", "shellfish");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("Tater tots", "Fats");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("Toast", "wheat");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("Venison", "Friut");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("Waffles", "pork");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("Wine", "poultry");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("Walnuts", "poultry");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("Yogurt", "wheat");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("Ziti", "meat");
INSERT INTO ingredient (ingredient_name, food_group) VALUES("Zucchini", "beef");
