INSERT INTO measurement (measurement_name) VALUES ("Cup");
INSERT INTO measurement (measurement_name) VALUES ("Teaspoon");
INSERT INTO measurement (measurement_name) VALUES ("Tablespoon");
INSERT INTO measurement (measurement_name) VALUES ("Pound");
INSERT INTO measurement (measurement_name) VALUES ("Quart");
INSERT INTO measurement (measurement_name) VALUES ("Ounce");
INSERT INTO measurement (measurement_name) VALUES ("Pint");
INSERT INTO measurement (measurement_name) VALUES ("Millilitre");
INSERT INTO measurement (measurement_name) VALUES ("Litre");
INSERT INTO measurement (measurement_name) values ('g');
INSERT INTO measurement (measurement_name) values ('cup');
INSERT INTO measurement (measurement_name) values ('kg');
INSERT INTO measurement (measurement_name) values ('n/a');

INSERT INTO ingredients (ingredient_name) VALUES("apples");
INSERT INTO ingredients (ingredient_name) VALUES("avacado");
INSERT INTO ingredients (ingredient_name) VALUES("alfalfa");
INSERT INTO ingredients (ingredient_name) VALUES("acorn squash");
INSERT INTO ingredients (ingredient_name) VALUES("almond");
INSERT INTO ingredients (ingredient_name) VALUES("arugala");
INSERT INTO ingredients (ingredient_name) VALUES("artichoke");
INSERT INTO ingredients (ingredient_name) VALUES("applesauce");
INSERT INTO ingredients (ingredient_name) VALUES("asian noodles");

INSERT INTO meal (meal_name, meal_type, num_calorie, day) VALUES("Lemon drizzle cake", "Breakfast", 689, "Friday");
INSERT INTO meal (meal_name, meal_type, num_calorie, day) VALUES("Ultimate chocolate cake", "Breakfast", 1310, "Sunday");
INSERT INTO meal (meal_name, meal_type, num_calorie, day) VALUES("Chilli con carne", "Lunch", 547, "Tuesday");
INSERT INTO meal (meal_name, meal_type, num_calorie, day) VALUES("Yummy scrummy carrot cake", "Breakfast", 1727, "Tuesday");
INSERT INTO meal (meal_name, meal_type, num_calorie, day) VALUES("Best-ever brownies", "Breakfast", 928, "Saturday");
INSERT INTO meal (meal_name, meal_type, num_calorie, day) VALUES("Spiced carrot & lentil soup", "Dinner", 1233, "Thursday");
INSERT INTO meal (meal_name, meal_type, num_calorie, day) VALUES("Chicken & chorizo jambalaya", "Breakfast", 1010, "Wednesday");
INSERT INTO meal (meal_name, meal_type, num_calorie, day) VALUES("Summer-in-winter chicken", "Breakfast", 1253, "Saturday");
INSERT INTO meal (meal_name, meal_type, num_calorie, day) VALUES("Spicy root & lentil casserole", "Breakfast", 591, "Sunday");
INSERT INTO meal (meal_name, meal_type, num_calorie, day) VALUES("Mustard-stuffed chicken", "Lunch", 1982, "Sunday");
INSERT INTO meal (meal_name, meal_type, num_calorie, day) VALUES("Classic scones with jam & clotted cream", "Lunch", 268, "Monday");
INSERT INTO meal (meal_name, meal_type, num_calorie, day) VALUES("Red lentil, chickpea & chilli soup", "Lunch", 1060, "Saturday");
INSERT INTO meal (meal_name, meal_type, num_calorie, day) VALUES("Falafel burgers", "Dinner", 682, "Sunday");
INSERT INTO meal (meal_name, meal_type, num_calorie, day) VALUES("Chicken biryani", "Breakfast", 886, "Tuesday");
INSERT INTO meal (meal_name, meal_type, num_calorie, day) VALUES("Raspberry Bakewell cake", "Dinner", 1731, "Friday");
INSERT INTO meal (meal_name, meal_type, num_calorie, day) VALUES("Chocolate brownie cake", "Dinner", 796, "Monday");
INSERT INTO meal (meal_name, meal_type, num_calorie, day) VALUES("Classic Victoria sandwich", "Dinner", 355, "Thursday");
INSERT INTO meal (meal_name, meal_type, num_calorie, day) VALUES("Creamy courgette lasagne", "Breakfast", 281, "Monday");
INSERT INTO meal (meal_name, meal_type, num_calorie, day) VALUES("One-pot chicken chasseur", "Dinner", 344, "Wednesday");
INSERT INTO meal (meal_name, meal_type, num_calorie, day) VALUES("Unbelievably easy mince pies", "Breakfast", 945, "Monday");
INSERT INTO meal (meal_name, meal_type, num_calorie, day) VALUES("Asian Grilled Salmon", "Lunch", 1560, "Sunday");
INSERT INTO meal (meal_name, meal_type, num_calorie, day) VALUES("Chicken Parmesan", "Lunch", 1121, "Sunday");
INSERT INTO meal (meal_name, meal_type, num_calorie, day) VALUES("Macaroni and Cheese", "Breakfast", 1140, "Wednesday");
INSERT INTO meal (meal_name, meal_type, num_calorie, day) VALUES("Chicken Pot Pie", "Lunch", 1498, "Wednesday");
INSERT INTO meal (meal_name, meal_type, num_calorie, day) VALUES("Chicken Cacciatore", "Dinner", 1281, "Tuesday");
INSERT INTO meal (meal_name, meal_type, num_calorie, day) VALUES("Salisbury Steak", "Lunch", 1361, "Sunday");
INSERT INTO meal (meal_name, meal_type, num_calorie, day) VALUES("Chocolate Pretzel Peanut Butter Squares", "Lunch", 1942, "Sunday");
INSERT INTO meal (meal_name, meal_type, num_calorie, day) VALUES("Blackberry Cobbler", "Breakfast", 1194, "Thursday");
INSERT INTO meal (meal_name, meal_type, num_calorie, day) VALUES("Roast Chicken", "Lunch", 354, "Friday");
INSERT INTO meal (meal_name, meal_type, num_calorie, day) VALUES("Sweet and Sour Chicken", "Lunch", 1087, "Wednesday");
INSERT INTO meal (meal_name, meal_type, num_calorie, day) VALUES("Restaurant-Style Salsa", "Dinner", 1799, "Sunday");
INSERT INTO meal (meal_name, meal_type, num_calorie, day) VALUES("Shrimp Scampi with Linguini", "Lunch", 1991, "Friday");
INSERT INTO meal (meal_name, meal_type, num_calorie, day) VALUES("Parmesan-Crusted Pork Chops", "Dinner", 1264, "Sunday");
INSERT INTO meal (meal_name, meal_type, num_calorie, day) VALUES("Broccoli Cheese Soup", "Dinner", 1948, "Saturday");
INSERT INTO meal_plan (mealplan_id, end_date) VALUES(1, "1986-06-16");
INSERT INTO meal_plan (mealplan_id, end_date) VALUES(2, "1993-04-27");
INSERT INTO meal_plan (mealplan_id, end_date) VALUES(3, "1989-02-20");
INSERT INTO meal_plan (mealplan_id, end_date) VALUES(4, "2000-03-11");
INSERT INTO meal_plan (mealplan_id, end_date) VALUES(5, "1990-06-05");
INSERT INTO meal_plan (mealplan_id, end_date) VALUES(6, "2014-06-06");
INSERT INTO meal_plan (mealplan_id, end_date) VALUES(7, "1986-02-07");
INSERT INTO meal_plan (mealplan_id, end_date) VALUES(8, "2003-10-17");
